### ISSUE TITLE
很喜欢这个主题

### ISSUE THREAD

**Issue by zhjr2019** [yahweh042/flat-theme#2]
![Snipaste_2022-04-15_16-58-03](https://user-images.githubusercontent.com/44044519/163550194-30774c9e-22b2-49d3-84b3-741096836535.png)
希望打开脚本后的效果如下，
![Snipaste_2022-04-15_16-58-11](https://user-images.githubusercontent.com/44044519/163550246-970d010e-5bd9-4b98-9436-2697130904d4.png)

**Comment by yahweh042** [comment]
这个颜色统一了 不利于代码的查看
